### ISSUE TITLE
Suggestion : add Page lineage with level and path

### ISSUE THREAD

**Issue by zakrevskyi** [jaewilson07/domo_library#98]
hi @jaewilson07 ,

thank you for get children method for Page class. It would be also really helpful to know the level (1-3) and know the path of the particular page (is it sub page, or top page or sub sub page)?

Thank you

**Comment by jaewilson07** [comment]
this has been implemented with the flatten_children method

https://github.com/jaewilson07/domo_library/blob/main/domolibrary/classes/DomoPage.py#L343
